Modificado alguns termos do documento.
Viniciustertuliano/eng-soft pull request #21
Opened 2020-08-15 19:12 UTC by Viniciustertuliano

## Descrição
Editado alguns termos e corrigido erro de escrita.

2020-08-15 20:55 UTC, abmport approved these changes

2020-08-15 20:57 UTC, abmport approved these changes

2020-08-17 10:43 UTC, LauraTazue approved these changes

2020-08-19 14:40 UTC, isabellamota requested changes
a

2020-08-19 14:59 UTC, isabellamota approved these changes

2020-08-19 15:03 UTC, merged